export const homObjOne = {
  id: "story",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topline: "DAMN BOOY",
  headline: "Lucille Is Thirsty Ma Boi",
  description: "She Is A Vampire-bat booooy",
  buttonLabel: "lucille Bat",
  imgStart: false,
  img: require("../../images/art.png"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homObjTwo = {
  id: "gallery",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topline: "EIEN PROJECT",
  headline: "this is eien project",
  description: "fucking hell",
  buttonLabel: "not a button",
  imgStart: true,
  img: require("../../images/art-2.png"),
  alt: "Art",
  dark: false,
  primary: false,
  darkText: true,
};

export const homObjThree = {
  id: "roadmap",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topline: "DAMN BOOY",
  headline: "Lucille Is Thirsty Ma Boi",
  description: "She Is A Vampire-bat booooy",
  buttonLabel: "lucille Bat",
  imgStart: false,
  img: require("../../images/art-3.png"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
